### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by thomasbnt** [jclusso/strapi-plugin-netlify-deployments#11]
Hello! I followed the process installation, and configured with Build hooks the plugin. 
But when I build and restart Strapi server, I've got this error on :
- /admin/plugins/netlify-deployments
- /admin/settings/netlify-deployments : 
```
[2024-01-15 19:57:35.700] http: GET /netlify-deployments/config (35 ms) 500
[2024-01-15 19:57:35.714] error: Cannot read properties of undefined (reading 'length')
TypeError: Cannot read properties of undefined (reading 'length')
     at truncateSensitiveString (/strapi/node_modules/strapi-plugin-netlify-deployments/server/services/utils.js:14:14)
     at buildConfig (/strapi/node_modules/strapi-plugin-netlify-deployments/server/services/utils.js:30:18)
     at Object.getConfig (/strapi/node_modules/strapi-plugin-netlify-deployments/server/services/config.js:16:13)
     at Object.getConfig (/strapi/node_modules/strapi-plugin-netlify-deployments/server/controllers/config.js:5:71)
     at dispatch (/strapi/node_modules/koa-compose/index.js:42:32)
     at returnBodyMiddleware (/strapi/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js:42:24)
     at dispatch (/strapi/node_modules/koa-compose/index.js:42:32)
     at policiesMiddleware (/strapi/node_modules/@strapi/strapi/dist/services/server/policy.js:15:11)
     at dispatch (/strapi/node_modules/koa-compose/index.js:42:32)
     at /strapi/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js:27:18
 [2024-01-15 19:57:35.714] http: GET /netlify-deployments/config (42 ms) 500
``` 

Node version : v18.17.1

**Comment by jclusso** [comment]
Hey @thomasbnt, unfortunatly I no longer use Strapi. If I had to guess I'd assume your config might be missing one of the keys that are considered sensative because the error is happening inside the `truncateSensitiveString` method.

https://github.com/jclusso/strapi-plugin-netlify-deployments/blob/9603dd8ef9a8b9adf0623593b194bac69a128778/server/services/utils.js#L13-L20

If there is a bug, I'm happy to review an accept a PR.

**Comment by thomasbnt** [comment]
> Hey @thomasbnt, unfortunatly I no longer use Strapi. If I had to guess I'd assume your config might be missing one of the keys that are considered sensative because the error is happening inside the `truncateSensitiveString` method.
> 
> https://github.com/jclusso/strapi-plugin-netlify-deployments/blob/9603dd8ef9a8b9adf0623593b194bac69a128778/server/services/utils.js#L13-L20
> 
> If there is a bug, I'm happy to review an accept a PR.

Thanks for your reply! My `admin/server.js` was badly written! It's fixed!
